Remove aliases created by buildx when installing by default
docker/setup-buildx-action pull request #139
Opened 2022-04-25 07:04 UTC by hashhar

If the action is configured to install buildx by default using the
input then docker buildx sets up docker build as an alias for buildx
making all docker build calls use the buildx builder instead of
traditional builders. The action didn't perform cleanup in this case to
uninstall the aliases which meant that any future workflows running on
same GitHub Actions runner would get the buildx builders even if it did
not explicitly request it.

This commit tracks if the aliases were installed and removes them during
post step of the action if so.

Fixes https://github.com/docker/setup-buildx-action/issues/125

2022-04-26 07:23 UTC, hashhar commented
Thanks for approving the CI run @tonistiigi. Looks green (kind of expected since no tests exist for the cleanup part and I couldn't figure out how to add one).

Let me know if there's something more you'd like me to do.

2023-06-06 12:02 UTC, crazy-max requested changes
Sorry for the delay! Needs a rebase and adapt following changes that have been made recently, thanks!

2024-09-15 18:31 UTC, hashhar commented
I've addressed the comments. PTAL @crazy-max. I eventually came back to this while cleaning up my open PRs.

2025-05-21 10:03 UTC, crazy-max approved these changes
LGTM thanks!

Pushed extra commit to update generated content.

2025-05-21 10:04 UTC, merged