Support to retain cache
docker/setup-buildx-action pull request #211
Opened 2023-02-27 18:17 UTC by ibalajiarun

This PR adds support to keep the cache state when the builder is removed in the post-action step. For certain usecases such as CI builds, it is helpful to keep the cache and reuse it with re-created builders. 

To support cache reuse, this PR also allows specifying a custom name to the builder, since cache reuse is no possible with the exiting random names generated using `uuid.v4()`.

2023-04-17 23:04 UTC, ibalajiarun commented
Hey @crazy-max , can I get a review on this one?

2023-04-18 22:12 UTC, ibalajiarun commented
/cc @jedevc

2023-04-19 06:42 UTC, crazy-max reviewed
Sorry for the delay. I left some comments.

Also have you tested this change on your side? Keeping the BuildKit state will only work on persistent runners and not public ones that are ephemeral. If this is your intent then it should be documented to avoid confusion.

2023-04-19 06:42 UTC, crazy-max commented on src/context.ts
> +  if (customName && customName.length > 0) {
```suggestion
  if (customName) {
```

2023-04-19 06:42 UTC, crazy-max commented on src/state-helper.ts
> +export const keepState = process.env['STATE_keepState'] || false;
```suggestion
export const keepState = !!process.env['STATE_keepState'];
```

2023-04-19 06:42 UTC, crazy-max commented on action.yml
> +  custom-name:
I'm not sure about naming this `custom-name`, this is confusing. Better to follow the buildx UX of the [create command](https://docs.docker.com/engine/reference/commandline/buildx_create/) and use `name`.

2023-04-19 16:00 UTC, ibalajiarun commented
Thanks for the review @crazy-max. I've addressed your feedback.

We have been using this change at [aptos-labs/aptos-core](https://github.com/aptos-labs/aptos-core) for over a month now with persistent self-hosted runners and have seen speed ups of up to 50% in build times.

https://github.com/aptos-labs/aptos-core/blob/751153f20f3068ed71cfe3d79ab9fe0212cc4107/.github/actions/docker-setup/action.yaml#L41-L58

2023-05-31 04:17 UTC, ibalajiarun commented
@crazy-max can we get this merged please?

2023-06-02 11:55 UTC, crazy-max reviewed
Sorry got pending reviews I forgot to submit :persevere:

It would be better if we have another PR for the `name` input being added.

2023-06-02 11:55 UTC, crazy-max commented on src/context.ts
> +    name: getBuilderName(core.getInput('name'), core.getInput('driver') || 'docker-container'),
`name` needs to be defined in https://github.com/docker/setup-buildx-action/blob/master/action.yml. Also needs to update README to add this new input.

2023-12-27 18:00 UTC, zpiazza-combocurve commented
Any movement on this?

2024-03-26 10:01 UTC, tobiaszuercher commented
just stumpled upon this, the `--keep-state` flag in docker buildx rm for self-hosted runners could speed up builds drastically.

what is needed to get any movement on this?

2024-06-13 20:19 UTC, rarecrumb commented
@ibalajiarun @crazy-max can we take another look at this? Would be great to have.

2024-07-05 15:09 UTC, nelyodev commented
This PR might be the missing piece of my ultimate caching pipeline quest. Any chance it will be merged in the near future?

2024-09-19 14:45 UTC, tobiaszuercher commented
@ibalajiarun @crazy-max is there something still open? happy to contribute

2025-05-20 11:43 UTC, crohr commented on src/context.ts
> +    name: getBuilderName(core.getInput('name'), core.getInput('driver') || 'docker-container'),
Being able to set a custom name would help with reusing the builder's cache across CI runs (assuming e.g. `/var/lib/docker` can be restored across runs). Would be even better if it could also check for an env var so that CI platforms (e.g. [RunsOn](https://runs-on.com)) can automatically set it without user intervention.

2025-05-21 09:50 UTC, crazy-max requested changes

2025-05-21 09:50 UTC, crazy-max commented on action.yml
> +    description: 'Keep state on cleanup'
```suggestion
    description: 'Keep BuildKit state on cleanup. This is only useful on persistent self-hosted runners.'
```

2025-05-21 09:50 UTC, crazy-max commented on action.yml
> +    description: 'Builder name use use when creating the builder. If not specified, one will be generated. Specifying a name enables reusing a buildkit volume in persistent self-hosted runners.'
Last sentence not needed for this input but should be added to `keep-state` (see previous comment).

```suggestion
    description: 'Builder name set when creating the builder. If not specified, one will be generated.'
```

2025-05-21 09:50 UTC, crazy-max commented on src/context.ts
> +  return driver == 'docker' ? 'default' : `builder-${uuid.v4()}`;
Why changing `await Docker.context()` to `default`? It might not always be default so we should keep that.

2025-05-21 09:50 UTC, crazy-max commented on src/main.ts
> +          const rmCmd = await buildx.getCommand(['rm', stateHelper.builderName, stateHelper.keepState ? '--keep-state' : '']);
Although cobra should manage empty arg we should avoid this:

```suggestion
          const rmCmd = await buildx.getCommand(['rm', stateHelper.builderName, ...(stateHelper.keepState ? ['--keep-state'] : [])]);
```

2025-05-21 09:50 UTC, crazy-max commented on src/state-helper.ts
> +export const keepState = !!process.env['STATE_keepState'];
Missing newline

2025-05-27 21:49 UTC, ibalajiarun commented on src/context.ts
> +  if (name) {
That makes sense. Updated.

2025-06-02 18:24 UTC, crohr commented
Hi @crazy-max, any chance to get a final review on this? Thanks!

2025-06-11 19:34 UTC, crohr commented
This change is now used by https://github.com/runs-on/snapshot to make buildkit caches persistent across ephemeral runner jobs. Would be great to get it merged so that I can point to the official action tag :)

2025-06-13 18:57 UTC, closed without merging